# Generated by Django 3.2 on 2022-10-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='spouse_name',
            new_name='college',
        ),
    ]
