# Generated by Django 4.1.1 on 2022-10-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="sponsor_logos")),
                ("url", models.URLField()),
            ],
        ),
    ]
