# Generated by Django 4.1.1 on 2022-10-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_workshop"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("sub_title", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=200)),
                ("details", models.TextField()),
                ("brochure_link", models.URLField()),
                ("register_link", models.URLField()),
                ("image", models.ImageField(upload_to="workshop_images")),
                ("register_timestamp", models.DateTimeField()),
                ("start_timestamp", models.DateTimeField()),
                ("end_timestamp", models.DateTimeField()),
                ("event_complete", models.BooleanField(default=False)),
                ("venue", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Exhibition",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("summary", models.CharField(max_length=250)),
                ("details", models.TextField()),
                ("image", models.ImageField(upload_to="workshop_images")),
                ("start_timestamp", models.DateTimeField()),
                ("end_timestamp", models.DateTimeField()),
                ("venue", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="GuestTalk",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("guest_name", models.CharField(max_length=100)),
                ("summary", models.CharField(max_length=250)),
                ("details", models.TextField()),
                ("register_link", models.URLField()),
                ("image", models.ImageField(upload_to="workshop_images")),
                ("register_timestamp", models.DateTimeField()),
                ("start_timestamp", models.DateTimeField()),
                ("end_timestamp", models.DateTimeField()),
                ("venue", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Mechandise",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="mechandise_images")),
                ("price", models.FloatField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="OrganisingTeamMember",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="team_images")),
                ("designation", models.CharField(max_length=100)),
                ("linkedin", models.URLField()),
                ("contact", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="workshop",
            name="venue",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Winner",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("position", models.IntegerField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.event"
                    ),
                ),
            ],
        ),
    ]
