# Generated by Django 4.1.1 on 2022-10-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_event_exhibition_guesttalk_mechandise_notification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("departmental", "Departmental"),
                    ("informal", "Informal"),
                    ("club", "Club"),
                ],
                default="departmental",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
