# Generated by Django 4.1.1 on 2022-10-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_event_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(upload_to="event_images"),
        ),
        migrations.AlterField(
            model_name="exhibition",
            name="image",
            field=models.ImageField(upload_to="exhibition_images"),
        ),
        migrations.AlterField(
            model_name="guesttalk",
            name="image",
            field=models.ImageField(upload_to="guest_images"),
        ),
    ]
