# Generated by Django 4.1.1 on 2022-10-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_event_image_alter_exhibition_image_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Mechandise", new_name="Merchandise",),
    ]
